version: "2"

services:
  pwaTest:
    labels:
      - traefik.http.routers.pwaTest.middlewares=https-redirectscheme
      - "traefik.http.routers.pwaTest-secure.rule=Host(`pwa.magicorp.fr`)"
      - traefik.http.routers.pwaTest-secure.tls=true
      - traefik.http.routers.pwaTest-secure.tls.certresolver=sslresolver